---

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install docker prerequisites
  apt:
    name: [apt-transport-https, ca-certificates, curl, software-properties-common, python3-pip]
    state: present

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: get ubuntu release name like focal, jammy
  shell: cat /etc/os-release | grep UBUNTU_CODENAME | sed 's/UBUNTU_CODENAME=//'
  register: results

- set_fact:
    code: "{{ results.stdout }}"

- name: Then add the GPG key for the official Docker repository to your system
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add the Docker repository to APT sources
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update your existing list of packages again for the addition to be recognized
  shell: apt update

- name: Make sure you are about to install from the Docker repo instead of the default Ubuntu repo
  shell: apt-cache policy docker-ce

- name: Install docker prerequisites
  apt:
    name: [docker-ce]
    state: present
